#!/usr/bin/env node
/**
 * Live validation of the runtime modes.
 *
 * ---------------------------------------------------------------------------
 * WHAT THIS PROVES THAT THE HERMETIC SUITE CANNOT
 * ---------------------------------------------------------------------------
 * `npm test` proves the cockpit *transmits* the right bytes: `/lens cfo …`,
 * `/council ceo,cfo …`, `/begin`. It cannot prove the engine *honours* them,
 * because honouring them happens inside the model.
 *
 * So this drives the compiled production runtime — the same
 * `dist-electron/electron/bridge/claude-cli.js` the packaged application runs —
 * against real repositories and reads what actually comes back.
 *
 * These are **behavioural spot-checks, not deterministic tests.** The engine's
 * wording varies between runs, so each check asserts something structural about
 * the response rather than matching prose. A failure here is a signal to read the
 * transcript, not automatically a defect.
 *
 * Costs real tokens. Never points at production for anything that writes.
 *
 *   npm run build:electron
 *   node scripts/validate-modes.mjs
 */

import { createRequire } from 'node:module';
import { cp, mkdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { diffFingerprints, fingerprintGuarded, GUARDED } from './lib/fingerprint.mjs';

const require = createRequire(import.meta.url);
const { ClaudeCliRuntime } = require('../dist-electron/electron/bridge/claude-cli.js');
const { composeTurn, councilMode, lensMode, ONBOARDING_TURN, DEFAULT_COUNCIL_MODE } = require(
  '../dist-electron/shared/runtime-modes.js'
);

const HERE = path.dirname(fileURLToPath(import.meta.url));
const GUI = path.resolve(HERE, '..');
const PRODUCTION = path.resolve(GUI, '..');

/** An established repository — has Business Memory. */
const ESTABLISHED = process.env.EIS_SANDBOX ?? path.resolve(PRODUCTION, '..', 'eis-sandbox');

/** A repository with no Business Memory, for the first-run path. */
const FIRST_RUN = path.resolve(PRODUCTION, '..', 'eis-firstrun-sandbox');

let pass = 0;
let fail = 0;
let warn = 0;

function check(label, condition, detail = '') {
  if (condition) {
    pass += 1;
    console.log(`  PASS  ${label}`);
  } else {
    fail += 1;
    console.log(`  FAIL  ${label}${detail ? ` — ${detail}` : ''}`);
  }
}

/** A soft expectation: reported, but not a release blocker on its own. */
function observe(label, condition, detail = '') {
  if (condition) {
    pass += 1;
    console.log(`  PASS  ${label}`);
  } else {
    warn += 1;
    console.log(`  WARN  ${label}${detail ? ` — ${detail}` : ''}`);
  }
}

async function exists(target) {
  try {
    await stat(target);
    return true;
  } catch {
    return false;
  }
}

/** Build a disposable repository with no Business Memory. */
async function makeFirstRunRepo() {
  await rm(FIRST_RUN, { recursive: true, force: true });
  await mkdir(FIRST_RUN, { recursive: true });
  for (const entry of ['CLAUDE.md', 'core', 'docs', '.claude']) {
    const from = path.join(PRODUCTION, entry);
    if (await exists(from)) await cp(from, path.join(FIRST_RUN, entry), { recursive: true });
  }
  // The whole point of this repository: the file the engine treats as first-run
  // evidence must be absent.
  await rm(path.join(FIRST_RUN, 'core', 'business_memory.md'), { force: true });
  await writeFile(
    path.join(FIRST_RUN, 'SANDBOX.md'),
    '# Disposable first-run sandbox\n\nGenerated by gui/scripts/validate-modes.mjs. Not production.\n',
    'utf8'
  );
}

/** Send one turn and resolve with the complete reply text. */
function turn(workspacePath, text, mode, timeoutMs = 240_000) {
  return new Promise((resolve) => {
    const events = [];
    const runtime = new ClaudeCliRuntime((event) => events.push(event));

    void runtime.open({ workspacePath }).then(async () => {
      await runtime.send(text, mode);

      const started = Date.now();
      const tick = setInterval(async () => {
        const done = events.some((e) => e.kind === 'turn-complete');
        const fatal = events.some((e) => e.kind === 'error' && e.fatal);
        if (!done && !fatal && Date.now() - started < timeoutMs) return;

        clearInterval(tick);
        await runtime.close();

        const complete = events.filter((e) => e.kind === 'message-complete');
        resolve({
          text: complete.map((e) => e.text).join('\n'),
          events,
          completed: done,
        });
      }, 300);
    });
  });
}

async function main() {
  console.log('runtime mode validation');
  console.log(`established: ${ESTABLISHED}`);
  console.log(`first run:   ${FIRST_RUN}`);
  console.log('');

  /* ----------------------------------------------------------- safety first */
  console.log('[0] safety');
  check('established sandbox exists', await exists(ESTABLISHED));
  check(
    'sandboxes are NOT the production repository',
    path.resolve(ESTABLISHED) !== PRODUCTION && path.resolve(FIRST_RUN) !== PRODUCTION
  );
  const before = fingerprintGuarded(PRODUCTION);
  check('production fingerprinted', before.size > 0, `${before.size} files`);
  if (fail > 0) {
    console.log('\nsafety checks failed; refusing to run');
    process.exit(1);
  }

  await makeFirstRunRepo();
  check('first-run sandbox has no Business Memory',
    !(await exists(path.join(FIRST_RUN, 'core', 'business_memory.md'))));

  /* ------------------------------------------------- 1. advisor speaks first */
  console.log('\n[1] /begin — first run, advisor speaks first');
  {
    const composed = composeTurn(ONBOARDING_TURN, DEFAULT_COUNCIL_MODE);
    check('the onboarding turn is the bare command', composed === '/begin', composed);

    const reply = await turn(FIRST_RUN, ONBOARDING_TURN, DEFAULT_COUNCIL_MODE);
    check('the turn completed', reply.completed);
    check('the advisor produced the first message', reply.text.trim().length > 0,
      `${reply.text.length} chars`);

    /*
     * Onboarding entered, judged by what it says it is doing.
     *
     * An earlier version of this check tested for a question mark, which flagged a
     * perfectly good opening — "Before we start deciding anything together, I need
     * to understand your business" — as a soft failure. Punctuation is not the
     * property; entering onboarding is.
     */
    observe('it enters onboarding rather than answering a question',
      /(understand your business|before we|first run|get to know|tell me about)/i.test(reply.text));
    observe('it does not narrate its own boot',
      !/^(loading|reading|initialis|initializ)/i.test(reply.text.trim()));

    console.log(`\n  --- reply (first 400 chars) ---\n  ${reply.text.slice(0, 400).replace(/\n/g, '\n  ')}\n`);
  }

  /* ----------------------------------------------------- 2. single-lens mode */
  console.log('\n[2] /lens — one executive, no council');
  {
    const composed = composeTurn('Is a 30% price rise defensible?', lensMode('cfo'));
    check('the lens directive precedes the message',
      composed.startsWith('/lens cfo\n\n'), composed.slice(0, 40));

    const reply = await turn(ESTABLISHED, 'Is a 30% price rise defensible?', lensMode('cfo'));
    check('the turn completed', reply.completed);
    check('a reply arrived', reply.text.trim().length > 0);

    // Structural, not prose: a single-lens answer attributes itself to that lens
    // and does not present the other executives' positions.
    observe('it identifies itself as the CFO perspective', /\bCFO\b/i.test(reply.text));
    observe('no other constructive lens states a position',
      !/\b(COO|Sales\/GTM|Product lens|Coach)\b.*\b(argues|adds|notes|position)\b/i.test(reply.text));
    observe('no challenge-lens pass is presented',
      !/(Devil'?s Advocate|Risk Officer)\s*[:—-]/i.test(reply.text));
    observe('it is not delivered as a full Executive Action Memo',
      !(/What Must Be True/i.test(reply.text) && /Considered & Rejected/i.test(reply.text)));

    console.log(`\n  --- reply (first 500 chars) ---\n  ${reply.text.slice(0, 500).replace(/\n/g, '\n  ')}\n`);
  }

  /* ------------------------------------------------- 3. restricted council */
  console.log('\n[3] /council — a disabled executive stays out');
  {
    const available = ['ceo', 'cfo', 'coo', 'sales-gtm', 'product', 'coach'];
    // Sales/GTM disabled, then asked a question its own row would normally lead.
    const mode = councilMode(['ceo', 'cfo', 'coo', 'product'], available);
    const composed = composeTurn('Should we change our pricing and packaging?', mode);

    check('the council directive lists only enabled executives',
      composed.startsWith('/council ceo,cfo,coo,product\n\n'), composed.slice(0, 48));
    check('the disabled executive is not transmitted', !composed.includes('sales-gtm'));

    const reply = await turn(ESTABLISHED, 'Should we change our pricing and packaging?', mode);
    check('the turn completed', reply.completed);
    check('a reply arrived', reply.text.trim().length > 0);

    // The command instructs the engine to say when the restriction cost something.
    // That disclosure is the observable evidence the set was honoured.
    observe('it discloses routing without the disabled executive',
      /sales|gtm/i.test(reply.text) &&
        /(without|absent|disabled|not engaged|excluded|unavailable)/i.test(reply.text));

    console.log(`\n  --- reply (first 500 chars) ---\n  ${reply.text.slice(0, 500).replace(/\n/g, '\n  ')}\n`);
  }

  /* -------------------------------------------------- 4. repository write audit */
  console.log('\n[4] repository write audit');
  const changed = diffFingerprints(before, fingerprintGuarded(PRODUCTION));
  check(
    `production ${GUARDED.join('/, ')}/ byte-identical`,
    changed.length === 0,
    changed.join('; ')
  );

  // No interface configuration may have landed in the sandboxes' own core/ either.
  for (const repo of [ESTABLISHED, FIRST_RUN]) {
    for (const leak of ['enabledLenses', 'noticeDismissed', 'eis-cockpit-ui']) {
      const hit = await exists(path.join(repo, 'core', leak));
      check(`no ${leak} artifact in ${path.basename(repo)}/core`, !hit);
    }
  }

  console.log('');
  console.log(`${pass} passed, ${fail} failed, ${warn} soft`);
  console.log(`\nfirst-run sandbox left at ${FIRST_RUN} for inspection; delete when done.`);
  process.exit(fail > 0 ? 1 : 0);
}

main().catch((error) => {
  console.error('harness error:', error);
  process.exit(1);
});
