/**
 * Electron main process — the host shell.
 *
 * Responsibilities, and nothing beyond them:
 *   - create one window
 *   - serve the statically exported renderer over a privileged `app://` scheme
 *   - expose a minimal, explicitly enumerated IPC surface
 *
 * Milestone 1 exposes no filesystem access and no process spawning. Those
 * arrive with the bridge (M2) and the repository projections (M3), each behind
 * a narrow, validated channel. Nothing here knows what an executive is.
 */

import { app, BrowserWindow, dialog, ipcMain, protocol, shell } from 'electron';
import { createReadStream, statSync } from 'node:fs';
import { stat } from 'node:fs/promises';
import path from 'node:path';
import { ConversationStore } from './conversations';
import { createSplash, dismiss } from './splash';
import { RepositoryReader } from './repo';
import { RuntimeManager } from './runtime/manager';
import { CredentialStore } from './runtime/auth/credentials';
import {
  createWorkspace,
  openWorkspace,
  repairWorkspace,
  resolveEngineSource,
  validateWorkspace,
} from './workspace';
import { readConversationMode, type PersistedMessage } from '../shared/conversations';
import { parseRuntimeMode } from '../shared/runtime-modes';
import { parseDeepLink, PROTOCOL, routeForIntent } from '../shared/deeplink';
import { resolveIconPath } from '../shared/icon';
import { Readable } from 'node:stream';

const IS_DEV = process.env.EIS_DEV === '1';
const DEV_URL = 'http://localhost:3000';

/**
 * Static export output.
 *
 * Compiled layout is `dist-electron/electron/main.js` (tsc preserves the source
 * tree because `shared/` is also compiled), so the app root is two levels up.
 */
const OUT_DIR = path.join(__dirname, '..', '..', 'out');

/** Application root — one level above `dist-electron/`. */
const APP_DIR = path.join(__dirname, '..', '..');

/**
 * Resolve the window icon, preferring the founder's own asset.
 *
 * `gui/icon.png` is the source of truth; `build/icon.png` is what
 * `scripts/prepare-icon.mjs` derives from it, and is also where the placeholder
 * lands when no real icon has been provided. Returning undefined is a supported
 * outcome — Electron falls back to its default and nothing crashes, which is
 * what lets a fresh clone run before an icon exists.
 *
 * On Windows the packaged executable carries its own icon from electron-builder,
 * so this mainly matters in development and on Linux.
 */
function resolveWindowIcon(): string | undefined {
  return resolveIconPath(
    [
      path.join(APP_DIR, 'icon.png'),
      path.join(APP_DIR, 'build', 'icon.png'),
      path.join(process.resourcesPath ?? APP_DIR, 'icon.png'),
    ],
    (candidate) => statSync(candidate).isFile()
  );
}

/**
 * Hashes of the inline scripts in the current build, generated by
 * `scripts/csp-hashes.mjs` immediately after `next build`.
 *
 * Next's export bootstraps and hydrates from inline `<script>` tags. Under a
 * `script-src` with no allowance for them Chromium refused every one, and the
 * packaged app rendered static HTML that never became interactive. Hashing them
 * admits exactly those scripts and still refuses any other inline script.
 *
 * An empty list is a safe failure: the policy stays strict and the app does not
 * hydrate, which is loud. It is never widened to `'unsafe-inline'`.
 */
function readScriptHashes(): string[] {
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const hashes = require(path.join(OUT_DIR, 'csp-hashes.json')) as unknown;
    if (!Array.isArray(hashes)) return [];
    return hashes.filter((h): h is string => typeof h === 'string');
  } catch {
    console.error('[eis] csp-hashes.json missing — the renderer will not hydrate.');
    return [];
  }
}

/**
 * Content Security Policy for the packaged renderer.
 *
 * `'unsafe-inline'` for styles is required by Next's injected critical CSS.
 * Scripts get no such allowance — they are admitted individually, by hash. No
 * remote origins are permitted at all: this application is entirely local, so
 * any outbound request is a defect.
 */
const CSP = [
  "default-src 'self' app:",
  ["script-src 'self' app:", ...readScriptHashes()].join(' '),
  "style-src 'self' app: 'unsafe-inline'",
  "img-src 'self' app: data:",
  // The startup animation. Stated explicitly rather than left to `default-src`,
  // so that narrowing the default later cannot silently break the splash.
  "media-src 'self' app:",
  "font-src 'self' app: data:",
  "connect-src 'self' app:",
  "object-src 'none'",
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "form-action 'none'",
].join('; ');

/*
 * Must run before `app.ready`. Marking the scheme `standard` gives it normal
 * URL semantics; `secure` places it in a secure context so the renderer is not
 * treated as untrusted content.
 */
protocol.registerSchemesAsPrivileged([
  {
    scheme: 'app',
    privileges: {
      standard: true,
      secure: true,
      supportFetchAPI: true,
      /*
       * Required for `<video>`.
       *
       * Chromium's media stack issues byte-range requests and will not decode
       * from a custom scheme that has not declared itself streamable — the
       * element fires `error` within a couple of milliseconds and never plays.
       * Without this the splash "worked" in the sense that it degraded to
       * nothing, on every launch, on every platform.
       */
      stream: true,
    },
  },
]);

const MIME: Record<string, string> = {
  '.html': 'text/html',
  '.js': 'text/javascript',
  '.mjs': 'text/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.webp': 'image/webp',
  /*
   * The startup animation.
   *
   * Without this entry the handler fell back to `application/octet-stream`, and
   * a `<video>` given an opaque binary type refuses to decode it — the splash
   * failed instantly with an `error` event and the app launched with no
   * animation at all. It degraded gracefully, which is exactly why nobody would
   * have noticed: the only visible symptom was the absence of a feature.
   */
  '.mp4': 'video/mp4',
  '.webm': 'video/webm',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ico': 'image/x-icon',
};

/**
 * Resolve a request path to a file inside OUT_DIR.
 *
 * Returns null for anything that escapes OUT_DIR. Directory requests resolve
 * to `index.html`, which is how Next's `trailingSlash` export layout works.
 */
async function resolveAsset(urlPath: string): Promise<string | null> {
  // Strip query and fragment. Indexing is guarded because `noUncheckedIndexedAccess`
  // is on and `split` can, in principle, yield an empty array.
  const stripped = urlPath.split('?')[0] ?? '';
  const decoded = decodeURIComponent(stripped.split('#')[0] ?? '');
  const candidate = path.join(OUT_DIR, decoded);

  // Path-traversal guard: the resolved target must stay within OUT_DIR.
  const resolved = path.resolve(candidate);
  const root = path.resolve(OUT_DIR);
  if (resolved !== root && !resolved.startsWith(root + path.sep)) return null;

  try {
    const info = await stat(resolved);
    if (info.isDirectory()) {
      const index = path.join(resolved, 'index.html');
      await stat(index);
      return index;
    }
    return resolved;
  } catch {
    // Unknown path: fall back to the shell so client-side routing can recover.
    try {
      const fallback = path.join(root, 'index.html');
      await stat(fallback);
      return fallback;
    } catch {
      return null;
    }
  }
}

function registerAppProtocol(): void {
  protocol.handle('app', async (request) => {
    const { pathname } = new URL(request.url);
    const file = await resolveAsset(pathname === '/' ? '/index.html' : pathname);

    if (!file) {
      return new Response('Not found', {
        status: 404,
        headers: { 'content-type': 'text/plain' },
      });
    }

    const body = Readable.toWeb(createReadStream(file)) as ReadableStream;
    return new Response(body, {
      status: 200,
      headers: {
        'content-type': MIME[path.extname(file).toLowerCase()] ?? 'application/octet-stream',
        'content-security-policy': CSP,
      },
    });
  });
}

function createWindow(): BrowserWindow {
  const icon = resolveWindowIcon();

  const win = new BrowserWindow({
    width: 1180,
    height: 780,
    // 720 rather than 900: the cockpit is expected to hold a narrow layout, and a
    // minimum that forbids one means the narrow layout is never actually tested.
    minWidth: 720,
    minHeight: 600,
    show: false,
    ...(icon ? { icon } : {}),
    backgroundColor: '#0b0b0c',
    /*
     * ---------------------------------------------------------------------------
     * macOS TRAFFIC LIGHTS, SOLVED IN THE WINDOW RATHER THAN IN CSS
     * ---------------------------------------------------------------------------
     * `hiddenInset` lifts the renderer into the title bar area, which is what
     * gives the app its continuous top edge — and it drops the three window
     * buttons on top of the sidebar wordmark. The tempting fix is a
     * platform-conditional left padding in React, which is a layout hack that
     * has to be re-tuned every time Apple moves the buttons.
     *
     * `trafficLightPosition` is the API that exists for this. The sidebar header
     * is 48px tall (`h-12`); centring a 16px-tall control cluster in it puts y at
     * 16, and x at 16 leaves the standard gutter. The wordmark then starts below
     * them rather than behind them, with no renderer-side knowledge of macOS.
     *
     * Windows and Linux keep their native frame: a custom title bar on those
     * platforms means reimplementing snap, maximise, and system menus badly.
     */
    ...(process.platform === 'darwin'
      ? { titleBarStyle: 'hiddenInset' as const, trafficLightPosition: { x: 16, y: 16 } }
      : {}),
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      // --- security posture: all three are load-bearing ---
      contextIsolation: true, // renderer cannot touch main's globals
      nodeIntegration: false, // no `require` in the renderer
      sandbox: true, // OS-level sandbox; preload uses contextBridge only
      webSecurity: true,
      allowRunningInsecureContent: false,
      devTools: IS_DEV,
    },
  });

  /*
   * The window is NOT shown here.
   *
   * `ready-to-show` means the renderer has painted, not that the application is
   * usable — the Next bundle still has to hydrate and the repository snapshot
   * still has to be read. Showing on this event is what would let the founder
   * see an unfinished UI. Reveal is coordinated in `startup()` against two
   * signals instead, and `EIS_SMOKE` waits for the same reveal so the smoke
   * check exercises the real path rather than a shortcut around it.
   */
  win.once('ready-to-show', () => {
    if (process.env.EIS_SMOKE === '1') {
      console.error('[smoke] ready-to-show fired');
    }
  });

  // Fail loudly rather than sitting behind an invisible window.
  win.webContents.on('did-fail-load', (_event, code, description, url) => {
    console.error(`[eis] renderer failed to load (${code} ${description}) ${url}`);
  });

  /*
   * Surface renderer errors during a smoke run.
   *
   * The window is hidden until it reports itself ready, so a renderer that
   * throws on mount is invisible in every sense — no window, no devtools, and a
   * host that patiently waits out its ceiling. Forwarding the console is the
   * only way a headless check can tell "still initialising" from "broken".
   */
  if (process.env.EIS_SMOKE === '1') {
    /*
     * Electron 34 changed this event's shape: it now passes a single event
     * object carrying `level` as a STRING, where it used to pass
     * `(event, level: number, message, line, sourceId)`.
     *
     * The old numeric comparison silently never matched, so the smoke harness
     * reported nothing while the renderer was throwing — which is precisely how
     * a renderer failure survived several launches looking like a splash-timing
     * problem. Both shapes are read, so this cannot go quiet again on either
     * side of an upgrade.
     */
    win.webContents.on('console-message', (...args: unknown[]) => {
      const [first, second, third] = args as [
        { level?: string | number; message?: string } | undefined,
        number | undefined,
        string | undefined,
      ];
      const level = typeof first?.level !== 'undefined' ? first.level : second;
      const message = first?.message ?? third ?? '';
      const serious = level === 'error' || level === 'warning' || (typeof level === 'number' && level >= 2);
      if (serious && message) console.error(`[smoke:renderer] ${level}: ${message}`);
    });

    win.webContents.on('preload-error', (_e, file, error) => {
      console.error(`[smoke:preload] ${file}: ${error.message}`);
    });

    win.webContents.on('render-process-gone', (_e, details) => {
      console.error(`[smoke:renderer] process gone: ${details.reason}`);
    });
  }

  // No in-app navigation away from our own origin.
  win.webContents.on('will-navigate', (event, url) => {
    const allowed = IS_DEV ? url.startsWith(DEV_URL) : url.startsWith('app://');
    if (!allowed) {
      event.preventDefault();
      void shell.openExternal(url);
    }
  });

  // No popups. External links go to the real browser, never a Chromium window.
  win.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:\/\//.test(url)) void shell.openExternal(url);
    return { action: 'deny' };
  });

  // Deny every permission request. A local cockpit needs no camera, mic,
  // geolocation, or notifications; anything asking is a bug or worse.
  win.webContents.session.setPermissionRequestHandler((_wc, _perm, callback) =>
    callback(false)
  );

  if (IS_DEV) {
    void win.loadURL(DEV_URL);
  } else {
    void win.loadURL('app://./index.html');
  }

  return win;
}

/**
 * IPC surface.
 *
 * Deliberately tiny: every channel is attack surface, so channels are enumerated
 * one at a time as features need them rather than exposing a general-purpose
 * escape hatch. Every argument crossing this boundary is validated here, because
 * the renderer is the untrusted side even when we wrote it.
 */
function registerIpc(getWindow: () => BrowserWindow | null, onRendererReady: () => void): void {
  /*
   * The renderer announcing that it is actually usable.
   *
   * `on`, not `handle`: this is a one-way notification with no reply, so there
   * is nothing for the renderer to await and no result it could act on. It
   * carries no payload for the same reason — the only fact being reported is
   * that the shell has mounted, and a message that cannot say anything else
   * cannot be used to say anything else.
   *
   * Fired once by `AppShell`. Extra fires are harmless: `reveal()` is
   * idempotent.
   */
  ipcMain.on('app:renderer-ready', () => onRendererReady());

  ipcMain.handle('host:info', () => ({
    appVersion: app.getVersion(),
    electronVersion: process.versions.electron,
    chromeVersion: process.versions.chrome,
    nodeVersion: process.versions.node,
    platform: process.platform,
    arch: process.arch,
    isDev: IS_DEV,
    repositoryUrl: readRepositoryUrl(),
    forceFirstRun: process.env.EIS_FORCE_FIRST_RUN === '1',
  }));

  /*
   * One runtime manager per host process, replacing the direct Claude transport.
   *
   * Every `advisor:*` channel below is unchanged — same names, same payloads, same
   * return shapes — because the manager implements the same surface the renderer
   * already consumed. That is the entire visible cost of making the runtime
   * replaceable, and it is the strongest evidence available that `advisor.ts` was
   * a real abstraction rather than a Claude interface with neutral names.
   */
  const credentials = CredentialStore.default();
  const runtime = new RuntimeManager((event) => {
    const win = getWindow();
    if (win && !win.isDestroyed()) win.webContents.send('advisor:event', event);
  }, credentials);

  /*
   * Discovery is NOT run here, and that is a deliberate reversal.
   *
   * Probing at startup spawned five `--version` subprocesses on every cold
   * launch, for a result nothing on screen was waiting for — and then the
   * first-run Discovery step scanned again the moment the founder reached it, so
   * a first launch paid for the work twice.
   *
   * It now runs when something actually asks: the Discovery step, the AI screen,
   * or an explicit Scan. The cost is that `runtime:snapshot` reports `unknown`
   * health until then, which is the honest value — nobody has looked — and is
   * exactly what the three-state capability system exists to represent.
   */

  // Directory picker. Returns a path only; the host never reads the directory
  // here, and the renderer cannot name a path the user did not choose.
  ipcMain.handle('host:selectDirectory', async () => {
    const win = getWindow();
    const result = win
      ? await dialog.showOpenDialog(win, {
          title: 'Choose your D.W.I.G.I workspace',
          properties: ['openDirectory'],
        })
      : await dialog.showOpenDialog({ properties: ['openDirectory'] });
    return result.canceled ? null : (result.filePaths[0] ?? null);
  });

  ipcMain.handle('advisor:isAvailable', () => runtime.isAvailable());

  ipcMain.handle('advisor:open', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.workspacePath !== 'string') {
      throw new Error('advisor:open requires a workspacePath string');
    }
    const resume =
      typeof payload.resumeSessionId === 'string' ? payload.resumeSessionId : undefined;
    return runtime.open({ workspacePath: payload.workspacePath, resumeSessionId: resume });
  });

  ipcMain.handle('advisor:send', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.text !== 'string') {
      throw new Error('advisor:send requires a text string');
    }
    /*
     * `text` is passed through unchanged. Trimming or normalising it here would
     * violate the verbatim-input invariant.
     *
     * `mode` is validated rather than trusted, and `parseRuntimeMode` degrades an
     * unrecognised value to the full Council rather than rejecting it. A
     * malformed mode must never be able to narrow a deliberation, because the
     * founder reading the answer would have no way to tell that it had.
     */
    return runtime.send(payload.text, parseRuntimeMode(payload.mode));
  });

  /*
   * The decision is validated against an explicit pair rather than cast.
   *
   * This value unblocks a stopped engine and decides whether a write happens.
   * The renderer is the untrusted side even though we wrote it, and anything
   * that is not literally `deny` must never be able to reach the runtime as an
   * approval — so the check is a whitelist, not a coercion.
   */
  ipcMain.handle('advisor:respondToPermission', (_e, payload: unknown) => {
    if (
      !isRecord(payload) ||
      typeof payload.requestId !== 'string' ||
      (payload.decision !== 'allow' && payload.decision !== 'deny')
    ) {
      throw new Error('advisor:respondToPermission requires requestId and decision');
    }
    return runtime.respondToPermission(payload.requestId, payload.decision);
  });

  ipcMain.handle('advisor:cancel', () => runtime.cancel());
  ipcMain.handle('advisor:close', () => runtime.close());
  ipcMain.handle('advisor:diagnostics', () => runtime.getDiagnostics());

  /*
   * ------------------------------------------------------------ AI providers
   *
   * The renderer reads manifests directly from `shared/runtime/manifests.ts`, so
   * these channels carry only *sampled* state — health, auth status, which brain
   * is active. Nothing here can return a credential: `submitApiKey` is one-way
   * inward, and every other channel returns a status enum at most.
   */
  ipcMain.handle('runtime:snapshot', () => runtime.snapshot());

  ipcMain.handle('runtime:detect', async () => {
    await runtime.detectAll();
    return runtime.snapshot();
  });

  ipcMain.handle('runtime:checkHealth', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.providerId !== 'string') {
      throw new Error('runtime:checkHealth requires a providerId string');
    }
    return runtime.checkHealth(payload.providerId);
  });

  ipcMain.handle('runtime:setActive', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.providerId !== 'string') {
      throw new Error('runtime:setActive requires a providerId string');
    }
    return runtime.setActive(payload.providerId);
  });

  /*
   * The one inbound path a secret takes.
   *
   * It goes renderer → main → OS keychain and never comes back. The result is a
   * boolean and an optional reason; there is deliberately no channel that reads a
   * stored key, so no amount of renderer compromise can retrieve one.
   */
  ipcMain.handle('runtime:submitApiKey', (_e, payload: unknown) => {
    if (
      !isRecord(payload) ||
      typeof payload.providerId !== 'string' ||
      typeof payload.secret !== 'string'
    ) {
      throw new Error('runtime:submitApiKey requires providerId and secret strings');
    }
    return runtime.submitApiKey(payload.providerId, payload.secret);
  });

  ipcMain.handle('runtime:disconnect', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.providerId !== 'string') {
      throw new Error('runtime:disconnect requires a providerId string');
    }
    return runtime.disconnect(payload.providerId);
  });

  /*
   * -------------------------------------------------------------- workspaces
   *
   * `validate` and `create` take a path the founder chose through the OS picker,
   * which is the only way a path enters this application. Nothing here accepts a
   * path from a deep link — see the protocol handler, which carries no path at all.
   */
  ipcMain.handle('workspace:validate', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.target !== 'string') {
      throw new Error('workspace:validate requires a target string');
    }
    return validateWorkspace(payload.target);
  });

  ipcMain.handle('workspace:create', async (_e, payload: unknown) => {
    if (
      !isRecord(payload) ||
      typeof payload.target !== 'string' ||
      typeof payload.name !== 'string'
    ) {
      throw new Error('workspace:create requires target and name strings');
    }
    const engine = await resolveEngineSource(process.resourcesPath, APP_DIR);
    return createWorkspace({
      target: payload.target,
      name: payload.name,
      appVersion: app.getVersion(),
      engine,
      now: new Date().toISOString(),
    });
  });

  ipcMain.handle('workspace:open', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.target !== 'string') {
      throw new Error('workspace:open requires a target string');
    }
    return openWorkspace({
      target: payload.target,
      appVersion: app.getVersion(),
      now: new Date().toISOString(),
    });
  });

  ipcMain.handle('workspace:repair', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.target !== 'string') {
      throw new Error('workspace:repair requires a target string');
    }
    return repairWorkspace(payload.target);
  });

  /*
   * Repository reader. READ-ONLY: there is no write channel here, and adding one
   * would break the architecture's guarantee that only the advisor mutates the
   * repository.
   */
  const repo = new RepositoryReader(() => {
    const win = getWindow();
    if (win && !win.isDestroyed()) win.webContents.send('repo:changed');
  });

  ipcMain.handle('repo:setWorkspace', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.workspacePath !== 'string') {
      throw new Error('repo:setWorkspace requires a workspacePath string');
    }
    return repo.setWorkspace(payload.workspacePath);
  });

  ipcMain.handle('repo:snapshot', () => repo.snapshot());

  ipcMain.handle('repo:reveal', async (_e, payload: unknown) => {
    // Opens a folder in the OS file manager. Confined to the workspace, and
    // cannot open an arbitrary path the renderer names.
    const root = repo.getWorkspace();
    if (!root) return false;
    const sub = isRecord(payload) && typeof payload.relative === 'string' ? payload.relative : '';
    const target = path.resolve(root, sub);
    if (target !== root && !target.startsWith(root + path.sep)) return false;
    await shell.openPath(target);
    return true;
  });

  /*
   * Conversation transcripts.
   *
   * The root is fixed here, once, to the host's own application-data directory.
   * No IPC method below accepts a path — the renderer names conversations by id
   * and nothing else — so this channel cannot be steered at the repository. That
   * is the whole of the fence between the cockpit's one write path and the
   * advisor's files.
   */
  const conversations = new ConversationStore(
    path.join(app.getPath('userData'), 'conversations')
  );

  ipcMain.handle('conversations:list', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.workspacePath !== 'string') {
      throw new Error('conversations:list requires a workspacePath string');
    }
    return conversations.list(payload.workspacePath);
  });

  ipcMain.handle('conversations:create', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.workspacePath !== 'string') {
      throw new Error('conversations:create requires a workspacePath string');
    }
    // `mode` is normalised by the store, which defaults anything unrecognised to
    // Council. `title` is length-clamped there as well.
    return conversations.create(payload.workspacePath, {
      mode: readConversationMode(payload.mode),
      title: typeof payload.title === 'string' ? payload.title : undefined,
    });
  });

  ipcMain.handle('conversations:load', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.id !== 'string') {
      throw new Error('conversations:load requires an id string');
    }
    return conversations.load(payload.id);
  });

  ipcMain.handle('conversations:append', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.id !== 'string') {
      throw new Error('conversations:append requires an id string');
    }
    if (!Array.isArray(payload.messages)) {
      throw new Error('conversations:append requires a messages array');
    }
    // Shape is checked here rather than trusted, because a malformed record
    // would be written to disk and read back later as if it were a real message.
    const messages: PersistedMessage[] = payload.messages.map((entry, index) => {
      if (
        !isRecord(entry) ||
        typeof entry.id !== 'string' ||
        (entry.role !== 'user' && entry.role !== 'advisor') ||
        typeof entry.text !== 'string' ||
        typeof entry.createdAt !== 'number'
      ) {
        throw new Error(`conversations:append message ${index} is malformed`);
      }
      return {
        id: entry.id,
        role: entry.role,
        text: entry.text,
        createdAt: entry.createdAt,
      };
    });
    return conversations.append(payload.id, messages);
  });

  ipcMain.handle('conversations:bindSession', (_e, payload: unknown) => {
    if (
      !isRecord(payload) ||
      typeof payload.id !== 'string' ||
      typeof payload.sessionId !== 'string'
    ) {
      throw new Error('conversations:bindSession requires id and sessionId strings');
    }
    return conversations.bindSession(payload.id, payload.sessionId);
  });

  ipcMain.handle('conversations:rename', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.id !== 'string' || typeof payload.title !== 'string') {
      throw new Error('conversations:rename requires id and title strings');
    }
    return conversations.rename(payload.id, payload.title);
  });

  // Session reset (v1.2.3 Part I). A flag flip, never a deletion — see
  // `ConversationStore.archive`.
  ipcMain.handle('conversations:archive', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.id !== 'string') {
      throw new Error('conversations:archive requires an id string');
    }
    return conversations.archive(payload.id);
  });

  ipcMain.handle('conversations:remove', (_e, payload: unknown) => {
    if (!isRecord(payload) || typeof payload.id !== 'string') {
      throw new Error('conversations:remove requires an id string');
    }
    return conversations.remove(payload.id);
  });

  app.on('before-quit', () => repo.stopWatching());

  // Release the child process on shutdown rather than orphaning it.
  app.on('before-quit', () => {
    void runtime.close();
  });
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

/**
 * The project's repository URL, from its own `package.json`.
 *
 * Read rather than hardcoded, and null rather than guessed: an interface that
 * invents a plausible GitHub URL sends founders to someone else's project. Only
 * `http(s)` is accepted, because the value ends up in `shell.openExternal`, and
 * a `git+ssh` or `file:` URL there would be handed to the operating system.
 */
function readRepositoryUrl(): string | null {
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const manifest = require(path.join(APP_DIR, 'package.json')) as {
      repository?: string | { url?: string };
    };
    const raw =
      typeof manifest.repository === 'string'
        ? manifest.repository
        : manifest.repository?.url;
    if (typeof raw !== 'string') return null;

    const cleaned = raw.replace(/^git\+/, '').replace(/\.git$/, '');
    return /^https?:\/\//.test(cleaned) ? cleaned : null;
  } catch {
    return null;
  }
}

/**
 * Register `dwigi://` with the operating system.
 *
 * In development the executable is Electron itself, so the registration has to
 * name this project's entry point explicitly or the OS would route every
 * `dwigi://` link to a bare Electron binary with no idea what to do with it.
 */
function registerProtocolClient(): void {
  if (process.defaultApp && process.argv.length >= 2) {
    const entry = process.argv[1];
    if (entry) {
      app.setAsDefaultProtocolClient(PROTOCOL, process.execPath, [path.resolve(entry)]);
      return;
    }
  }
  app.setAsDefaultProtocolClient(PROTOCOL);
}

/**
 * Pull a `dwigi://` URL out of a process argv.
 *
 * Windows and Linux deliver deep links as a command-line argument to a second
 * instance rather than through an event. The argument list also contains flags,
 * paths, and whatever else the shell passed, so the URL is *found* rather than
 * assumed to be last — an index-based read would pick up a flag the day Electron
 * adds one.
 */
function deepLinkFromArgv(argv: readonly string[]): string | null {
  return argv.find((arg) => arg.startsWith(`${PROTOCOL}://`)) ?? null;
}

// Single-instance: a second launch focuses the existing window.
if (!app.requestSingleInstanceLock()) {
  app.quit();
} else {
  let mainWindow: BrowserWindow | null = null;

  registerProtocolClient();

  /**
   * Route a validated deep link to the renderer.
   *
   * ---------------------------------------------------------------------------
   * WHAT CROSSES, AND WHAT CANNOT
   * ---------------------------------------------------------------------------
   * Only `{ intent, param?, path }` — an enum name, an already-validated short
   * identifier, and a renderer route. The original URL is deliberately **not**
   * forwarded: nothing downstream has a reason to re-parse it, and a raw URL
   * sitting in the renderer is an invitation for a future component to do exactly
   * that and reach a different conclusion than the validator did.
   *
   * A rejected link is reported to the founder rather than silently dropped. A
   * link that appears to do nothing is indistinguishable from a broken
   * application, and the reason — unknown route, reserved for a later version — is
   * something they can act on.
   */
  const handleDeepLink = (raw: string | null): void => {
    if (!raw) return;

    const result = parseDeepLink(raw);
    const win = mainWindow;
    if (!win || win.isDestroyed()) return;

    if (win.isMinimized()) win.restore();
    win.focus();

    if (!result.ok) {
      // Logged with the reason but WITHOUT the URL. A malicious link is untrusted
      // input, and writing it into a log the founder may later paste into an issue
      // would carry it further than it should go.
      console.error(`[eis] deep link rejected (${result.kind}): ${result.reason}`);
      win.webContents.send('deeplink:rejected', { kind: result.kind, reason: result.reason });
      return;
    }

    const route = routeForIntent(result.intent);
    if (!route) {
      console.error(`[eis] deep link intent "${result.intent.intent}" has no screen mapped`);
      return;
    }

    win.webContents.send('deeplink:navigate', {
      intent: result.intent.intent,
      ...(result.intent.param !== undefined ? { param: result.intent.param } : {}),
      path: route,
    });
  };

  app.on('second-instance', (_event, argv) => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    }
    // Windows and Linux: the link arrives as an argument to the second instance.
    handleDeepLink(deepLinkFromArgv(argv));
  });

  // macOS delivers it as an event, to the running instance, at any time.
  app.on('open-url', (event, url) => {
    event.preventDefault();
    handleDeepLink(url);
  });

  /**
   * Bring up the splash and the application together, and reveal the
   * application when both the animation and the renderer are done.
   *
   * ---------------------------------------------------------------------------
   * THE TWO GATES, AND THE CEILING OVER BOTH
   * ---------------------------------------------------------------------------
   * The window appears when the animation has finished AND the renderer has
   * reported itself ready. Whichever lands second decides the moment: a fast
   * machine waits for the video, a slow one keeps the splash up past the end of
   * playback rather than exposing a half-built screen.
   *
   * `STARTUP_CEILING_MS` sits above both. If either gate never reports — a
   * renderer that threw during hydration, a splash page that never ran — the
   * application is shown anyway. **A broken splash must never be able to hide a
   * working application**, and a broken renderer should be visible so it can be
   * diagnosed rather than concealed behind an animation that loops forever.
   */
  const STARTUP_CEILING_MS = 20_000;

  /**
   * Shortest time the splash stays up.
   *
   * Below this it reads as a flicker rather than a deliberate opening — the
   * window appears to stutter on launch instead of arriving.
   */
  const SPLASH_MIN_MS = 900;

  /**
   * Longest the splash may hold a *ready* application back.
   *
   * ---------------------------------------------------------------------------
   * MEASURED, THEN CHANGED. THE ORIGINAL RULE WAS COSTING TEN SECONDS A LAUNCH.
   * ---------------------------------------------------------------------------
   * The first design revealed the window only when the animation had finished AND
   * the renderer had reported ready — "a fast machine waits for the video, a slow
   * one keeps the splash up past the end of playback". The second half of that is
   * still right and is still implemented. The first half was wrong, and it was
   * only visible once it was instrumented:
   *
   *     renderer ready at 686ms
   *     splash resolved via "ended" after 10048ms
   *     reveal via both gates at 10884ms
   *
   * The application was usable in under a second and every launch spent eleven
   * seconds on an animation. That is not a slow app; it is a fast app being held
   * shut, and on a product a founder opens several times a day it is the single
   * most expensive thing about the first impression.
   *
   * So the video is now a *floor and a ceiling* rather than a gate: the splash is
   * guaranteed to be seen, and it is never allowed to keep a ready window hidden
   * for longer than this. A slow renderer still holds the splash open, because
   * that half was always correct.
   */
  const SPLASH_MAX_HOLD_MS = 1_800;

  void app.whenReady().then(() => {
    // Registered in dev too, now: the splash is served over `app://` from the
    // static export, and only the main window's own URL differs by mode.
    registerAppProtocol();

    let revealed = false;
    let splash: ReturnType<typeof createSplash> = null;

    const launchedAt = Date.now();

    /** Show the application and retire the splash. Safe to call repeatedly. */
    const reveal = (why: string): void => {
      if (revealed) return;
      revealed = true;

      if (process.env.EIS_SMOKE === '1') {
        console.error(`[smoke] reveal via ${why} at ${Date.now() - launchedAt}ms`);
      }

      const win = mainWindow;
      if (win && !win.isDestroyed()) {
        win.show();
        win.focus();
      }

      // After the window is up, so the fade happens over the application rather
      // than over the desktop.
      if (splash) void dismiss(splash);

      if (process.env.EIS_SMOKE === '1') {
        console.error('[smoke] application revealed');
        setTimeout(() => app.quit(), 1500);
      }
    };

    let rendererReady = false;
    let videoDone = false;

    /**
     * Reveal as soon as the application is genuinely usable, honouring the floor.
     *
     * Three ways in, and each is a real state rather than a fallback:
     *   - renderer ready and the floor elapsed  → the normal path
     *   - video ended and renderer ready        → a renderer slower than the video
     *   - the ceiling                           → something never reported
     */
    const revealIfReady = (why: string): void => {
      if (!rendererReady) return;
      const elapsed = Date.now() - launchedAt;
      if (elapsed >= SPLASH_MIN_MS) {
        reveal(why);
        return;
      }
      // Ready early. Hold for the remainder of the floor so the opening reads as
      // intentional rather than as a stutter.
      setTimeout(() => reveal(`${why} (after floor)`), SPLASH_MIN_MS - elapsed);
    };

    registerIpc(
      () => mainWindow,
      () => {
        if (process.env.EIS_SMOKE === '1' && !rendererReady) {
          console.error(`[smoke] renderer ready at ${Date.now() - launchedAt}ms`);
        }
        rendererReady = true;
        revealIfReady('renderer ready');
        // Ceiling on how long a *finished* app may be held behind the animation.
        setTimeout(() => revealIfReady('splash hold ceiling'), SPLASH_MAX_HOLD_MS);
      }
    );

    mainWindow = createWindow();

    /*
     * `app://` in both modes.
     *
     * The splash is a static file in the export, so it does not depend on the
     * Next dev server being up — which also means a `npm run dev` session that
     * has never run a web build simply fails to load it and starts immediately,
     * which is the documented degradation rather than a special case.
     */
    splash = createSplash('app://./splash.html');

    if (!splash) {
      // Could not even create the window. Nothing to wait for.
      videoDone = true;
      revealIfReady('no splash window');
    } else {
      void splash.finished.then(() => {
        videoDone = true;
        revealIfReady('video ended');
      });
    }

    setTimeout(() => reveal('startup ceiling'), STARTUP_CEILING_MS);

    /*
     * Cold start from a link: the application was launched *by* `dwigi://…`.
     *
     * Deferred until the renderer reports ready, because a navigation sent to a
     * window that has not mounted is delivered to nothing and lost — the link
     * would appear to have opened the app and then done nothing at all, which is
     * the most confusing possible outcome.
     */
    const coldStartLink = deepLinkFromArgv(process.argv);
    if (coldStartLink) {
      mainWindow.webContents.once('did-finish-load', () => handleDeepLink(coldStartLink));
    }

    app.on('activate', () => {
      if (BrowserWindow.getAllWindows().length === 0) {
        mainWindow = createWindow();
        // Reopened from the dock with no splash in play; show it directly.
        mainWindow.once('ready-to-show', () => mainWindow?.show());
      }
    });
  });

  app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') app.quit();
  });

  // Belt-and-braces: this app creates no <webview>, so any attempt to attach one
  // is either a bug or injected content. Refuse unconditionally, and strip any
  // preload it tried to bring with it.
  app.on('web-contents-created', (_event, contents) => {
    contents.on('will-attach-webview', (event, webPreferences) => {
      delete webPreferences.preload;
      webPreferences.nodeIntegration = false;
      event.preventDefault();
    });
  });
}
